name: syncfusion_flutter_sliders
description: Syncfusion Flutter Sliders library is written natively in Dart for creating highly interactive and UI-rich slider controls for filtering purposes.
version: 18.3.35-beta

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: 0.17.0
  syncfusion_flutter_core:
    git:
      url: https://github.com/darkgod1802/syncfusion_flutter_core.git

flutter: